/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as teamsManagerSol from "./TeamsManager.sol";
export { Administrable__factory } from "./Administrable__factory";
