/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as teamsManagerSol from "./TeamsManager.sol";
export type { teamsManagerSol };
export type { Administrable } from "./Administrable";
export * as factories from "./factories";
export { Administrable__factory } from "./factories/Administrable__factory";
export type { IERC20 } from "./TeamsManager.sol/IERC20";
export { IERC20__factory } from "./factories/TeamsManager.sol/IERC20__factory";
export type { TeamsManager } from "./TeamsManager.sol/TeamsManager";
export { TeamsManager__factory } from "./factories/TeamsManager.sol/TeamsManager__factory";
